name: Create Repository
on:
  issues:
    types: [opened]

jobs:
  create-repo:
    if: contains(github.event.issue.labels.*.name, 'repository-request')
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
        with:
          body: ${{ github.event.issue.body }}
      - run: |
          echo ${{ toJSON(steps.parse.outputs.data) }} jq -r '.["repository-name"].text

      - name: create repo
        uses: f1lander/create-repository-action@v1.0.2
        with:
          name: ${{ steps.parse.outputs.repo_name }}
          org: context.repo.owner
          access-token: ${{ secrets.REPO_TOKEN }}  # Optional        

      - name: Update issue status
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "Repository created successfully!"
          gh issue edit ${{ github.event.issue.number }} --state closed