name: Repository from CSV

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

on: [workflow_dispatch]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./tf

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: npm install
      run: |
        cd gh-automation
        npm install

    - name: Process Repositories
      run: node gh-automation/main.js
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_CREATE_TOKEN }}
        GITHUB_ORGANIZATION: ${{ github.repository_owner}}