name: Repository from CSV

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

on: [workflow_dispatch]


jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./gh-automation

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: npm install
      run: npm install

    - name: Process Repositories
      run: node main.js
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_CREATE_TOKEN }}
        GITHUB_ORGANIZATION: ${{ github.repository_owner}}