name: Terraform

on: []

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./tf

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.5

    - name: Terraform Init
      env:
        TF_LOG: "DEBUG"
        github_token: ${{ secrets.TF_TOKEN }}
        github_enterprise_slug: orgorgorgorgorg1
      run: |
        terraform init 

    - name: Terraform Plan
      env:
        TF_LOG: "DEBUG"
        github_token: ${{ secrets.TF_TOKEN }}
        github_enterprise_slug: orgorgorgorgorg1
      run: |
        terraform plan -var "github_enterprise_slug=orgorgorgorgorg1" -var "github_token=${{ secrets.TF_TOKEN }}" -out=tfplan
        
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      env:
        TF_LOG: "DEBUG"
      run: terraform apply -auto-approve tfplan
  