name: Terraform Init

on: [workflow_dispatch]

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID2 }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID2 }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID2 }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET2 }}"
  TF_LOG: TRACE
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./tf

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.5

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ secrets.TF_BACKEND_RG }}" \
          -backend-config="storage_account_name=${{ secrets.TF_BACKEND_SA_NAME }}" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform.tfstate" || export exitcode=$?
